### PR TITLE
Fix Variable in SkullOwner

### PR DESCRIPTION
**Pull request by wiljafor1**

### CODE REVIEW

**Comment by wiljafor1** [comment]
You can now use {player} in the SkullOwner field

**Comment by sgdc3** [comment]
Please don't change the identation style.

**Comment by sgdc3** [comment]
Also make sure to actually do it the right way, without causing a sync profile lookup that blocks the main thread.

**Comment by wiljafor1** [comment]
my git program bugged the upload, I'll clean it up when it's done right, I'll send a pull request

**Comment by wiljafor1** [comment]
The pull request was just what was modifying the file
https://github.com/wiljafor1/ChestCommands/commit/f7cdfb6b60a45d7a259939711c8beb561041b01c

**Comment by sgdc3** [comment]
could you try to rebase it correctly please?

**Comment by filoghost** [comment]
Also please don't change the class field inside the getter, use the setter.

**Comment by filoghost** [comment]
Added in https://github.com/filoghost/ChestCommands/pull/15

**Pull request closed without merging**
