### PR TITLE
Convert project to Maven

### PR DESCRIPTION
**Pull request by DoNotSpamPls**
This also includes:
.gitignore file
mcstats -> bstats conversion

PlayerPoints doesn't have a Maven repository, so I had to include the JAR file in the repo. If you build PlayerPoints on your Maven repo it can be removed.

### CODE REVIEW

**Comment by sgdc3** [comment]
I think PP support can be dropped, as it is an outdated resource.https://dev.bukkit.org/projects/playerpoints

**Comment by DoNotSpamPls** [comment]
@filoghost should I remove PlayerPoints support or leave it be?

**Comment by filoghost** [comment]
Thanks for the PR. I will review it later, I hope before the end of september.

You can remove PlayerPoints support.

**Comment by DoNotSpamPls** [comment]
@filoghost I have removed PlayerPoints support and am awaiting your review.

A sort of related question though: under which license would you like to release the plugin? Without a license, we don't even have rights to modify the code (making my changes technically illegal without your written permission, the same applies for HolographicDisplays too). For more information, check out https://choosealicense.org

**Comment by filoghost** [comment]
The license is on Bukkit Dev, but I will include it like I did with Holographic Displays. Thanks for the pull request, I have merged it and will be doing some changes in the near future.

HealthBar needs to be rewritten probably.

**Comment by sgdc3** [comment]
HelathBar conflicts with FeatherBoard a lot, would be cool if we find a solution...

**Pull request merged**
